/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio2;

import static java.lang.Thread.sleep;

/**
 *
 * @author Ralex-Pc
 */
public class HilosGrafico extends javax.swing.JFrame {

    pruebaconhilos hilo1 = new pruebaconhilos("Yo Soy Turino");
        pruebaconhilos hilo2 = new pruebaconhilos("Yo Soy Faby");
        Thread Hilo1 = new Thread(hilo1);
        Thread Hilo2 = new Thread(hilo2);
    /**
     * Creates new form HilosGrafico
     */
    public HilosGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IniciarHilo1_ = new javax.swing.JButton();
        DetenerHilo1_ = new javax.swing.JButton();
        IniciarHilo2_ = new javax.swing.JButton();
        DetenerHilo2_ = new javax.swing.JButton();
        IniciarHilos_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IniciarHilo1_.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        IniciarHilo1_.setText("Iniciar Hilo 1");
        IniciarHilo1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarHilo1_ActionPerformed(evt);
            }
        });

        DetenerHilo1_.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        DetenerHilo1_.setText("Detener Hilo 1");
        DetenerHilo1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerHilo1_ActionPerformed(evt);
            }
        });

        IniciarHilo2_.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        IniciarHilo2_.setText("Iniciar Hilo 2");
        IniciarHilo2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarHilo2_ActionPerformed(evt);
            }
        });

        DetenerHilo2_.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        DetenerHilo2_.setText("Deter Hilo 2");
        DetenerHilo2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerHilo2_ActionPerformed(evt);
            }
        });

        IniciarHilos_.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        IniciarHilos_.setText("Iniciar Hilos");
        IniciarHilos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarHilos_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IniciarHilo1_)
                    .addComponent(DetenerHilo1_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IniciarHilo2_)
                    .addComponent(DetenerHilo2_))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(IniciarHilos_)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IniciarHilo2_)
                        .addGap(47, 47, 47)
                        .addComponent(DetenerHilo2_))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IniciarHilo1_)
                        .addGap(47, 47, 47)
                        .addComponent(DetenerHilo1_)))
                .addGap(12, 12, 12)
                .addComponent(IniciarHilos_)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarHilo1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarHilo1_ActionPerformed
        Hilo1.resume();
    }//GEN-LAST:event_IniciarHilo1_ActionPerformed

    private void IniciarHilo2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarHilo2_ActionPerformed
        Hilo2.resume();
    }//GEN-LAST:event_IniciarHilo2_ActionPerformed

    private void DetenerHilo1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerHilo1_ActionPerformed
        Hilo1.suspend();
    }//GEN-LAST:event_DetenerHilo1_ActionPerformed

    private void DetenerHilo2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerHilo2_ActionPerformed
        Hilo2.suspend();
    }//GEN-LAST:event_DetenerHilo2_ActionPerformed

    private void IniciarHilos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarHilos_ActionPerformed
        this.Hilo1.start();
        this.Hilo2.start();
    }//GEN-LAST:event_IniciarHilos_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HilosGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetenerHilo1_;
    private javax.swing.JButton DetenerHilo2_;
    private javax.swing.JButton IniciarHilo1_;
    private javax.swing.JButton IniciarHilo2_;
    private javax.swing.JButton IniciarHilos_;
    // End of variables declaration//GEN-END:variables
}
