/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio2;

/**
 *
 * @author Ralex-Pc
 */
public class HilosGrafico extends javax.swing.JFrame {

    pruebaconhilos hilo1 = new pruebaconhilos("Chuchita");
    pruebaconhilos hilo2 = new pruebaconhilos("La bolsearon!!!");
    Thread Hilo1;
    Thread Hilo2;

    /**
     * Creates new form HilosGrafico
     */
    public HilosGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicia = new javax.swing.JButton();
        btnArrancar1 = new javax.swing.JButton();
        btnArrancar2 = new javax.swing.JButton();
        btnParar1 = new javax.swing.JButton();
        btnParar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInicia.setText("Iniciar Hilos");
        btnInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaActionPerformed(evt);
            }
        });

        btnArrancar1.setText("Arrarncar Hilo 1");
        btnArrancar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrancar1ActionPerformed(evt);
            }
        });

        btnArrancar2.setText("Arrancar Hilo 2");
        btnArrancar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrancar2ActionPerformed(evt);
            }
        });

        btnParar1.setText("Parar Hilo 1");
        btnParar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParar1ActionPerformed(evt);
            }
        });

        btnParar2.setText("Parar Hilo 2");
        btnParar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicia)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArrancar1)
                            .addComponent(btnArrancar2))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnParar2)
                            .addComponent(btnParar1))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnInicia)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArrancar1)
                    .addComponent(btnParar1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArrancar2)
                    .addComponent(btnParar2))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaActionPerformed
        this.Hilo1 = new Thread(hilo1);
        this.Hilo2 = new Thread(hilo2);
        Hilo1.start();
        Hilo2.start();
    }//GEN-LAST:event_btnIniciaActionPerformed

    private void btnArrancar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrancar1ActionPerformed

        Hilo1.resume();
    }//GEN-LAST:event_btnArrancar1ActionPerformed

    private void btnParar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParar1ActionPerformed

        Hilo1.suspend();
    }//GEN-LAST:event_btnParar1ActionPerformed

    private void btnParar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParar2ActionPerformed

        Hilo2.suspend();
    }//GEN-LAST:event_btnParar2ActionPerformed

    private void btnArrancar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrancar2ActionPerformed

        Hilo2.resume();
    }//GEN-LAST:event_btnArrancar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HilosGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HilosGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrancar1;
    private javax.swing.JButton btnArrancar2;
    private javax.swing.JButton btnInicia;
    private javax.swing.JButton btnParar1;
    private javax.swing.JButton btnParar2;
    // End of variables declaration//GEN-END:variables
}
