
package Unidad2;

import PantallaPrueba.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramon
 */
public class CalculoCurp extends javax.swing.JFrame {

    /**
     * Creates new form CalculoCurp
     */
    public CalculoCurp() {
        setResizable(false);
        initComponents();
        for(int i=1; i<=31; i++)
        {
            BoxDia.addItem(""+i);
        }
        
        for (int i = 01; i <= 12; i++)
        {
            if (i<10) {
               BoxMes.addItem("0"+i); 
            }
            else{
              BoxMes.addItem(""+i);  
            }
            
        }
        
         for (int i = 1990; i <= 2016; i++) {
            BoxAño.addItem(""+i);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlnombre = new javax.swing.JLabel();
        jlmaterno = new javax.swing.JLabel();
        jlpaterno = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        jlFecha = new javax.swing.JLabel();
        jlDia = new javax.swing.JLabel();
        jlMes = new javax.swing.JLabel();
        lbAño = new javax.swing.JLabel();
        BoxDia = new javax.swing.JComboBox();
        BoxMes = new javax.swing.JComboBox();
        BoxAño = new javax.swing.JComboBox();
        btnGen = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        boxGenero = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxEstado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlnombre.setText("NOMBRE");

        jlmaterno.setText("APELLIDO PATERNO");

        jlpaterno.setText("APELLIDO MATERNO");

        jlFecha.setText("FECHA DE NACIMIENTO");

        jlDia.setText("DIA");

        jlMes.setText("MES");

        lbAño.setText("AÑO");

        BoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDiaActionPerformed(evt);
            }
        });

        btnGen.setText("GENERAR");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });

        btnInicio.setText("INICIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        boxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        jLabel1.setText("Sexo");

        jLabel2.setText("Estado");

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JALISCO", "COLIMA", "MICHOACAN", "NAYARIT", "OAXACA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jlFecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnombre)
                            .addComponent(jlpaterno)
                            .addComponent(jlmaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtPaterno)
                            .addComponent(txtMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlDia)
                                .addGap(18, 18, 18)
                                .addComponent(BoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jlMes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lbAño)
                                .addGap(18, 18, 18)
                                .addComponent(BoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(98, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnGen)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmaterno)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpaterno)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDia)
                    .addComponent(jlMes)
                    .addComponent(lbAño)
                    .addComponent(BoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGen)
                    .addComponent(btnInicio))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDiaActionPerformed

    }//GEN-LAST:event_BoxDiaActionPerformed

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
       StringBuffer CurpCad = new StringBuffer();
        String n = txtNombre.getText().toUpperCase();
        String m = txtMaterno.getText().toUpperCase();
        String p = txtPaterno.getText().toUpperCase();
        String a = (String) BoxAño.getSelectedItem();
        String s = (String) boxGenero.getSelectedItem();
        String estado =  (String) boxEstado.getSelectedItem();
        CurpCad.append(p.charAt(0));
        
        for (int i = 1; i <=p.length(); i++) {
            if (p.charAt(i) == 'A' 
                    || p.charAt(i) == 'E'
                    || p.charAt(i) == 'I' 
                    || p.charAt(i) == 'O'
                    || p.charAt(i) == 'U') {
                CurpCad.append(p.charAt(i));
                break;    
            }
        }  
        CurpCad.append(m.charAt(0));
        CurpCad.append(n.charAt(0));
        String mes =  (String) BoxMes.getSelectedItem();
//        System.out.println(mes);
//        CurpCad.append(mes);
        CurpCad.append(a.charAt(a.length()-2));
        CurpCad.append(a.charAt(a.length()-1));
        CurpCad.append(mes);
        String dia =  (String) BoxDia.getSelectedItem();
        CurpCad.append(dia);
        CurpCad.append(s.charAt(0));
        if(boxEstado.getSelectedItem().equals("JALISCO"))
               CurpCad.append("JC");
        if(boxEstado.getSelectedItem().equals("COLIMA"))
               CurpCad.append("CM");
        if(boxEstado.getSelectedItem().equals("MICHOACAN"))
               CurpCad.append("OC");
        if(boxEstado.getSelectedItem().equals("COLIMA"))
               CurpCad.append("CM");
        if(boxEstado.getSelectedItem().equals("NAYARIT"))
               CurpCad.append("NT");
        
        for (int i = 1; i <=p.length(); i++) {
            if (p.charAt(i) != 'A' 
                    && p.charAt(i) != 'E'
                    && p.charAt(i) != 'I' 
                    && p.charAt(i) != 'O'
                    && p.charAt(i) != 'U') {
                CurpCad.append(p.charAt(i));
                break;
            }
        }

        for (int i = 1; i <=m.length(); i++) {
            if (p.charAt(i) != 'A' 
                    && m.charAt(i) != 'E'
                    && m.charAt(i) != 'I' 
                    && m.charAt(i) != 'O'
                    && m.charAt(i) != 'U') {
               CurpCad.append(m.charAt(i));
               break;
            }
        
         }
         for (int i = 1; i <=n.length(); i++) {
            if (p.charAt(i) != 'A' 
                    && n.charAt(i) != 'E'
                    && n.charAt(i) != 'I' 
                    && n.charAt(i) != 'O'
                    && n.charAt(i) != 'U') {
               CurpCad.append(n.charAt(i));
              break;
            }
        
         }

         JOptionPane.showMessageDialog(null, CurpCad);
    }//GEN-LAST:event_btnGenActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Principal menu = new Principal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoCurp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BoxAño;
    private javax.swing.JComboBox BoxDia;
    private javax.swing.JComboBox BoxMes;
    private javax.swing.JComboBox boxEstado;
    private javax.swing.JComboBox boxGenero;
    private javax.swing.JButton btnGen;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlMes;
    private javax.swing.JLabel jlmaterno;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel jlpaterno;
    private javax.swing.JLabel lbAño;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables
}
